services:
  codecrypto.traza-aceite: 
    container_name: trazabilidad-aceite.codecrypto
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trazabilidad-aceite.rule=host(`trazabilidad-aceite.codecrypto.academy`)"
      - "traefik.http.routers.trazabilidad-aceite.entrypoints=websecure"
      - "traefik.http.routers.trazabilidad-aceite.tls.certresolver=le"
      - "traefik.http.services.trazabilidad-aceite.loadbalancer.server.port=3004"
    networks:
      - academy-network
    restart: unless-stopped

networks:
  academy-network:
    external: true
